ProyectoMundoTronic/Controllers/ProyectoECommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data;
using System.Data.SqlClient;
using ProyectoMundoTronic.Models;
using ProyectoMundoTronic.DAO;
namespace ProyectoMundoTronic.Controllers
{
    public class ProyectoECommerceController : Controller
    {
        // GET: ProyectoECommerce
        //DAOS
        productoDAO productos = new productoDAO();
        ordenDAO ordenes = new ordenDAO();
        public ActionResult TiendaVirtual(string nombre ="")
        {
            if (Session["carroCompra"] == null)
                Session["carroCompra"] = new List<Item>();
 

            return View(productos.filtro(nombre));
        }
        public ActionResult Seleccionar(String codpro = "P001")
        {
            Producto reg = productos.Buscar(codpro);
            if (reg == null)
                return RedirectToAction("TiendaVirtual", new { nombre = "" });
            else
                ViewBag.d = (Session["carroCompra"] as List<Item>).Exists(p => p.codigo == codpro) ? true : false;
                

            return View(reg);
        }

     [HttpPost]
     public ActionResult Seleccionar(String codigo, int cantidad)
        {
            Producto reg = productos.Buscar(codigo);

            if (reg.stock< cantidad) {
                ViewBag.mensaje = "Debe agregar cantidad menor al stock";
                return View(reg);
            }
            else { 
            Item it = new Item()
            {
                codigo = codigo,
                nombre=reg.nombre,
                descripcion = reg.descripcion,
                categoria=reg.categoria,
                precio = reg.precio,
                cantidad = cantidad
            };

            (Session["carroCompra"] as List<Item>).Add(it);
            ViewBag.d = true; //deshabilitar la opcion Agregar

            ViewBag.mensaje = "Producto Agregado";

            return View(reg);
            }
        }

        public ActionResult Carrito()
        {

            if (Session["carroCompra"] == null)
                return RedirectToAction("TiendaVirtual", new { nombre = "" });
            else
                return View(Session["carroCompra"] as List<Item>);
        }

        [HttpPost]
        public ActionResult Actualizar(String codigo, int q)

        {
            Item reg =
                (Session["carroCompra"] as List<Item>).Where(p => p.codigo == codigo).FirstOrDefault();

            reg.cantidad = q;

            return RedirectToAction("Carrito");

        }
        
        public ActionResult Delete(String codigo)

        {

            Item reg = (Session["carroCompra"] as List<Item>).Find(p => p.codigo == codigo);

            (Session["carroCompra"] as List<Item>).Remove(reg);

            return RedirectToAction("Carrito");

        }

        public ActionResult Comprar()
        {
        
            if (Session["carroCompra"] == null)

                return RedirectToAction("TiendaVirtual", new { nombre = "" });
            else

                return View(new OrdenPedido());
        }
        [HttpPost]
        public ActionResult Comprar(OrdenPedido reg)

        {

            if ((Session["carroCompra"] as List<Item>).Count == 0)

            {

                ViewBag.mensaje = "Debe agregar productos a su canasta";

                return View(reg);

            }

            else

            {

                ViewBag.mensaje = ordenes.Transaccion(reg, Session["carroCompra"] as List<Item>);

                Session.Abandon(); //cerrar la sesion

                return View(reg);

            }

        }

        public ActionResult BuscarProductoPorDescripcion(string descripcion = "")
        {
            if (Session["carroCompra"] == null)
                Session["carroCompra"] = new List<Producto>();

            return View(productos.filtroDescripcion(descripcion));
        }
    }
}

ProyectoMundoTronic/Views/ProyectoECommerce/BuscarProductoPorDescripcion.cshtml
@model IEnumerable<ProyectoMundoTronic.Models.Producto>

@{
    ViewBag.Title = "BuscarProductoPorDescripcion";
}

<h2>BuscarProductoPorDescripcion</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codpro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.codpro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stock)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

ProyectoMundoTronic/Views/ProyectoECommerce/Carrito.cshtml
@model IEnumerable<ProyectoMundoTronic.Models.Item>

@{
    ViewBag.Title = "Carrito";
}
<!--Desactivar nav-->
<style>
    .navbar-fixed-top {
        display: none;
        visibility: hidden;
        height: 1px;
    }

        .navbar-fixed-top .container .collapse li a {
            color: black;
        }
</style>



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link href="~/css/estiloProductos.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>



<!--Navegador-->



<div class="scroll-up-btn">
    <i class="dedo fas fa-hand-point-up"></i>
</div>

<header>
    <div id="baner" style="max-width: 100%; min-width: 100%; margin:20px 0;">
        <img src="~/logo/banner1.jpg" alt="" />
        <img src="~/logo/banner2.jpg" alt="" />
        <img src="~/logo/banner3.jpg" alt="" />
        <img src="~/logo/banner4.jpg" alt="" />
    </div>
</header>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">


            <li class="nav-item active">

                <a class=" xd nav-link" href="#">
                    <span class=""><i class="icon fas fa-images"></i></span>Catálogo
                </a>
            </li>

            <li class="nav-item active">
                <a class="xd nav-link" href="/conocenos">
                    <span>
                        <i class="icon fas fa-users"></i>
                    </span>Conócenos
                </a>
            </li>


            <li class="nav-item dropdown">
                <a style="color: white;" class=" xd nav-link dropdown-toggle" href="#" aria-haspopup="true" id="navbarDropdown" aria-expanded="false" data-toggle="dropdown">
                    <span class=""><i class="icon fas fa-cogs"></i></span>Mantenimientos
                </a>

                <div style="margin-left: 60px;margin-top: 5px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/cargarProd">Productos</a>
                    <a class="dropdown-item" href="/cargarAdmi">Administrador</a>
                    <a class="dropdown-item" href="/cargarCli">Cliente</a>

                </div>
            </li>

        </ul>
    </div>
</nav>

<h2>Carrito</h2>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

<div id="todo">

    @Html.ActionLink("Ir a Tienda", "TiendaVirtual", new { nombre = "" }, new { @class = "btn btn-warning" }) |

    @Html.ActionLink("Ir a Comprar", "Comprar", null, new { @class = "btn btn-success" })

</div>

<br />

<br />

<style>
    .img-producto {
        width: 150px;
        height: 150px;
    }

    .img {
        position: relative;
        left: 600px;
        top: -300px;
    }


    .texto {
        font-size: 14px;
    }

    .producto span {
        color: crimson;
        font-size: 15px;
    }

    i {
        margin: 2px;
    }

    #todo a, #todo button, #todo input, #todo em {
        font-size: 15px;
    }
</style>

<table class="table texto">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>

            <!--Insertar form para ejecutar el actualizar-->
            <
                @using (Html.BeginForm("Actualizar", "ProyectoECommerce", FormMethod.Post))
                {
                    @Html.Hidden("codigo", item.codigo)
                    <td class="texto">
                        @Html.TextBox("q", item.cantidad, new { type = "number" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.monto)
                    </td>
                    <td class="texto">



                        <input type="submit" value="✓" class="bi bi-pencil-square btn btn-info texto" /> |

                        @Html.ActionLink(" ", "Delete", new { codigo = item.codigo }, new { onclick = "return confirm('Desea eliminar?');", @class = "bi bi-trash btn btn-danger" })

                    </td>
               
            }
        </tr>
    }
    <tr>
        <td colspan="4">Total de carrito de compras :</td>

        <td>@Model.Sum(i => i.monto) </td>
    </tr>
</table>


<!--Scripts-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/js/jquery-3.2.1.js"></script>
    <script src="~/js/jquery.cycle.all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>
    <script src="~/js/Productos.js"></script>
}

ProyectoMundoTronic/Views/ProyectoECommerce/Comprar.cshtml
@model ProyectoMundoTronic.Models.OrdenPedido

@{
    ViewBag.Title = "Comprar";
}
<!--Desactivar nav-->
<style>
    .navbar-fixed-top {
        display: none;
        visibility: hidden;
        height: 1px;
    }

        .navbar-fixed-top .container .collapse li a {
            color: black;
        }
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link href="~/css/estiloProductos.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>



<!--Navegador-->



<div class="scroll-up-btn">
    <i class="dedo fas fa-hand-point-up"></i>
</div>

<header>
    <div id="baner" style="max-width: 100%; min-width: 100%; margin:20px 0;">
        <img src="~/logo/banner1.jpg" alt="" />
        <img src="~/logo/banner2.jpg" alt="" />
        <img src="~/logo/banner3.jpg" alt="" />
        <img src="~/logo/banner4.jpg" alt="" />
    </div>
</header>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">


            <li class="nav-item active">

                <a class=" xd nav-link" href="#">
                    <span class=""><i class="icon fas fa-images"></i></span>Catálogo
                </a>
            </li>

            <li class="nav-item active">
                <a class="xd nav-link" href="/conocenos">
                    <span>
                        <i class="icon fas fa-users"></i>
                    </span>Conócenos
                </a>
            </li>


            <li class="nav-item dropdown">
                <a style="color: white;" class=" xd nav-link dropdown-toggle" href="#" aria-haspopup="true" id="navbarDropdown" aria-expanded="false" data-toggle="dropdown">
                    <span class=""><i class="icon fas fa-cogs"></i></span>Mantenimientos
                </a>

                <div style="margin-left: 60px;margin-top: 5px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/cargarProd">Productos</a>
                    <a class="dropdown-item" href="/cargarAdmi">Administrador</a>
                    <a class="dropdown-item" href="/cargarCli">Cliente</a>

                </div>
            </li>

        </ul>
    </div>
</nav>
<div style="text-align:center;">
    <h1>Comprar producto</h1>
    <h2>Datos cliente</h2>
</div>
<hr />
<style>
    .img-producto {
        width: 150px;
        height: 150px;
    }

    .img {
        position: relative;
        left: 600px;
        top: -300px;
    }


    .texto, .texto input {
        font-size: 16px;
    }

    .producto span {
        color: crimson;
        font-size: 15px;
    }

    i {
        margin: 2px;
    }

    #todo a, #todo button, #todo input, #todo em {
        font-size: 15px;
    }
</style>
<div style="width:100%;display:flex; align-content:center; justify-content:center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal texto">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group texto">
                @Html.LabelFor(model => model.cliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cliente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group texto">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group texto">
                @Html.LabelFor(model => model.fono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 texto">
                    @Html.EditorFor(model => model.fono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group ">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Comprar" class=" btn btn-default texto" /> <i class="bi bi-credit-card"></i> |
                    @Html.ActionLink("Ir a Tienda", "TiendaVirtual", new { nombre = "" }, new { @class = "btn btn-warning texto" })



                </div>
            </div>
        </div>
    }
</div>

<!-- Alerta -->
<div class="alert alert-danger  alert-dismissible show" role="alert">
    <strong style="font-size:14px; text-align:center">@ViewBag.mensaje</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span style="font-size:14px;" aria-hidden="true">&times;</span>
    </button>
</div>



<!--Scripts-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/js/jquery-3.2.1.js"></script>
    <script src="~/js/jquery.cycle.all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>
    <script src="~/js/Productos.js"></script>
}

ProyectoMundoTronic/Views/ProyectoECommerce/Seleccionar.cshtml
@model ProyectoMundoTronic.Models.Producto

@{
    ViewBag.Title = "Seleccionar";
}
<!--Desactivar nav-->
<style>
    .navbar-fixed-top {
        display: none;
        visibility: hidden;
        height: 1px;
    }

        .navbar-fixed-top .container .collapse li a {
            color: black;
        }
</style>



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link href="~/css/estiloProductos.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>



<!--Navegador-->



<div class="scroll-up-btn">
    <i class="dedo fas fa-hand-point-up"></i>
</div>

<header>
    <div id="baner" style="max-width: 100%; min-width: 100%; margin:20px 0;">
        <img src="~/logo/banner1.jpg" alt="" />
        <img src="~/logo/banner2.jpg" alt="" />
        <img src="~/logo/banner3.jpg" alt="" />
        <img src="~/logo/banner4.jpg" alt="" />
    </div>
</header>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">


            <li class="nav-item active">

                <a class=" xd nav-link" href="#">
                    <span class=""><i class="icon fas fa-images"></i></span>Catálogo
                </a>
            </li>

            <li class="nav-item active">
                <a class="xd nav-link" href="/conocenos">
                    <span>
                        <i class="icon fas fa-users"></i>
                    </span>Conócenos
                </a>
            </li>


            <li class="nav-item dropdown">
                <a style="color: white;" class=" xd nav-link dropdown-toggle" href="#" aria-haspopup="true" id="navbarDropdown" aria-expanded="false" data-toggle="dropdown">
                    <span class=""><i class="icon fas fa-cogs"></i></span>Mantenimientos
                </a>

                <div style="margin-left: 60px;margin-top: 5px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/cargarProd">Productos</a>
                    <a class="dropdown-item" href="/cargarAdmi">Administrador</a>
                    <a class="dropdown-item" href="/cargarCli">Cliente</a>

                </div>
            </li>

        </ul>
    </div>
</nav>




<style>
    .img-producto {
        width: 150px;
        height: 150px;
    }

    .img {
        position: relative;
        left: 600px;
        top: -300px;
    }


    .texto {
        font-size: 13px;
    }

    .producto span {
        color: crimson;
        font-size: 15px;
    }

    i {
        margin: 2px;
    }

    #todo a, #todo button, #todo input, #todo em {
        font-size: 15px;
    }
</style>
<div class="texto">
    <h3>Producto seleccionado : </h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.codpro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codpro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

    </dl>
</div>
<div id="todo" style="margin:30px 0">
    @using (Html.BeginForm())
    {

        @Html.Hidden("codigo", Model.codpro);
       
        <div style="margin-left:120px">
            <em style="margin-right:8px">Ingrese la cantidad : </em>
            @Html.TextBox("cantidad", 1, new { type = "number" })
        </div>
        <br />
        <div style="margin:10px 0">
            <input type="submit" value="Agregar" class="btn btn-success" disabled="@ViewBag.d" /> |
            @Html.ActionLink("Ir a la tienda", "TiendaVirtual", new { nombre = "" }, new { @class = "btn btn-warning" })
        </div>
    }
</div>

<br />

<!-- Alerta -->
<div class="alert alert-success  alert-dismissible show" role="alert">
    <strong style="font-size:14px; text-align:center">@ViewBag.mensaje</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span style="font-size:14px;"aria-hidden="true">&times;</span>
    </button>
</div>



<div class="img">
    <img src="@Url.Content(String.Format("~/ImgProd/{0}.jpg", Model.codpro))" class="img-producto" />
</div>

<!--Scripts-->
@section Scripts {
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/js/jquery-3.2.1.js"></script>
    <script src="~/js/jquery.cycle.all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.11/typed.min.js"></script>
    <script src="~/js/Productos.js"></script>
}